package ch.epfl.bluebrain.nexus.kg.resources

import ch.epfl.bluebrain.nexus.kg.resources.Ref.Latest
import ch.epfl.bluebrain.nexus.rdf.Iri.AbsoluteIri

/**
  * The unique id of a resource.
  *
  * @param parent        the parent reference of the resource identified by this id
  * @param value         the unique identifier for the resource within the referenced parent
  * @param autoGenerated flag which defines if this ''Id'' has been autogenerated or not
  */
final case class Id[P](parent: P, value: AbsoluteIri, autoGenerated: Boolean = false) {

  /**
    * @return a reference to this id
    */
  def ref: Ref =
    Latest(value)
}
